EJERCICIOS DE LECTURA DE FICHEROS

1. Actualiza el json de personal, añadiendo un año más a la edad y experiencia de cada registro de personal.

In [1]:
import json

import pandas as pd

In [2]:
with open("personal.json", "r") as fichero:

    personal = json.load(fichero)

In [3]:
type(personal)

dict

In [4]:
personal

{'workers': [{'nombre': 'Ana',
   'edad': 35,
   'experiencia': 6,
   'nivel': 'Senior',
   'salario': '50.000',
   'mascota': 'gatos'},
  {'nombre': 'Eva',
   'edad': 38,
   'experiencia': 3,
   'nivel': 'Mid',
   'salario': '25.000'},
  {'nombre': 'Marta',
   'edad': 28,
   'experiencia': 2,
   'nivel': 'Mid',
   'salario': '25.000'},
  {'nombre': 'Paula',
   'edad': 31,
   'experiencia': 4,
   'nivel': 'Senior',
   'salario': '50.000'}]}

In [5]:
for person in personal['workers']:
    print(person)

{'nombre': 'Ana', 'edad': 35, 'experiencia': 6, 'nivel': 'Senior', 'salario': '50.000', 'mascota': 'gatos'}
{'nombre': 'Eva', 'edad': 38, 'experiencia': 3, 'nivel': 'Mid', 'salario': '25.000'}
{'nombre': 'Marta', 'edad': 28, 'experiencia': 2, 'nivel': 'Mid', 'salario': '25.000'}
{'nombre': 'Paula', 'edad': 31, 'experiencia': 4, 'nivel': 'Senior', 'salario': '50.000'}


In [6]:
for worker in personal["workers"]:
    worker["edad"] += 1
    worker["experiencia"] +=1

personal

{'workers': [{'nombre': 'Ana',
   'edad': 36,
   'experiencia': 7,
   'nivel': 'Senior',
   'salario': '50.000',
   'mascota': 'gatos'},
  {'nombre': 'Eva',
   'edad': 39,
   'experiencia': 4,
   'nivel': 'Mid',
   'salario': '25.000'},
  {'nombre': 'Marta',
   'edad': 29,
   'experiencia': 3,
   'nivel': 'Mid',
   'salario': '25.000'},
  {'nombre': 'Paula',
   'edad': 32,
   'experiencia': 5,
   'nivel': 'Senior',
   'salario': '50.000'}]}

2. Cambia el nivel en función de la experiencia: Junior = 1 año, Mid = 2 o 3 años, Senior más de 4 años.

In [7]:
for worker in personal["workers"]:
    if worker["experiencia"] >= 4:
        worker["nivel"] = "Senior"
        
    elif worker["experiencia"] >= 2:
        worker["nivel"] = "Mid"
        
    else:
        worker["nivel"] = "Junior"

personal   

{'workers': [{'nombre': 'Ana',
   'edad': 36,
   'experiencia': 7,
   'nivel': 'Senior',
   'salario': '50.000',
   'mascota': 'gatos'},
  {'nombre': 'Eva',
   'edad': 39,
   'experiencia': 4,
   'nivel': 'Senior',
   'salario': '25.000'},
  {'nombre': 'Marta',
   'edad': 29,
   'experiencia': 3,
   'nivel': 'Mid',
   'salario': '25.000'},
  {'nombre': 'Paula',
   'edad': 32,
   'experiencia': 5,
   'nivel': 'Senior',
   'salario': '50.000'}]}

3. Cambia el salario en base al nivel: Junior = 25.000, Mid = 35.000, Senior = 50.000.

In [8]:
for worker in personal["workers"]:
    if worker["nivel"] == "Senior":
        worker["salario"] = "50.000"
        
    elif worker["experiencia"] == "Mid":
        worker["salario"] = "35.000"
        
    else:
        worker["salario"] = "25.000"

personal   

{'workers': [{'nombre': 'Ana',
   'edad': 36,
   'experiencia': 7,
   'nivel': 'Senior',
   'salario': '50.000',
   'mascota': 'gatos'},
  {'nombre': 'Eva',
   'edad': 39,
   'experiencia': 4,
   'nivel': 'Senior',
   'salario': '50.000'},
  {'nombre': 'Marta',
   'edad': 29,
   'experiencia': 3,
   'nivel': 'Mid',
   'salario': '25.000'},
  {'nombre': 'Paula',
   'edad': 32,
   'experiencia': 5,
   'nivel': 'Senior',
   'salario': '50.000'}]}

4. Guarda el json con el nombre "personal_actualizado.json".

In [9]:
with open("personal.json", "w") as personal_actualizado:
    json.dump(personal, personal_actualizado)

5. Abre el json con Pandas.

In [10]:
df = pd.read_json("personal_actualizado.json")

df

workers
0  {'nombre': 'Ana', 'edad': 35, 'experiencia': 6...
1  {'nombre': 'Eva', 'edad': 38, 'experiencia': 3...
2  {'nombre': 'Marta', 'edad': 28, 'experiencia':...
3  {'nombre': 'Paula', 'edad': 31, 'experiencia':...